name: exclude matrix strategy
on:
  workflow_dispatch

jobs:
   job1:
     strategy:
       matrix:
         os: [macos-latest, windows-latest]
         version: [12, 14, 16]
         environment: [staging, production]
         exclude:
           - os: macos-latest
             version: 12
             environment: production
           - os: windows-latest
             version: 16
     runs-on: ${{ matrix.os }}
    
    
