name: step output 
on:
  workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set output
        id: step1
        run: |
          echo "::set-output name=example_output::Hello from Step 1"
      
      - name: Use output in next step
        run: |
          echo "The output from the previous step was ${{ steps.step1.outputs.example_output }}"
