name: step output 
on:
  workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Set the value
        id: step1
        run: |
          echo "actionstate=yellow" >> "$GITHUB_ENV"
      
      - name: Use the value
        run: |
          echo "$actionstate"
