name: vars context in github
on:
  workflow_dispatch:

jobs:
  display-variables:
    runs-on: ubuntu-latest
    name: ${{ vars.JOB_NAME }}
    steps:
    - name: Use variables ${{ vars.ENV_CONTEXT_VAR }} 
      run: |
        echo "variable from shell environment : ${{ vars.ENV_CONTEXT_VAR }}"
        echo "job name is ${{ vars.JOB_NAME }}"

