name: vars context in github
on:
  workflow_dispatch:

env:
  # Use GitHub Actions environment variables correctly if needed
  env_var: ${{ vars.ENV_CONTEXT_VAR }}

jobs:
  display-variables:
    runs-on: ubuntu-latest
    name: ${{ vars.JOB_NAME }}
    steps:
    - name: Use variables
      run: |
        echo "variable from shell environment : $env_var"
        echo "job name is $name"

